### ISSUE TITLE
gradlew is not executable

### ISSUE THREAD

**Issue by rodislav** [deathbeam/yae#10]
Hello, when I'm trying to run:

```
java -jar non.jar gen:hello
```

I see this error:

```
Cannot run program "/home/rodislav/Projets/non-hello/.non/gradlew" (in directory ".non"): error=13, Permission denied
```

workaround is to go inside .non directory, change +x for gradlew (make it executable), can be done also from file properties / rights

Ubuntu 14.04, java 8

**Comment by deathbeam** [comment]
Hmm never tested this on Linux. Thanks for report. I have fix for this.

**Comment by deathbeam** [comment]
Fixes this in commit what I just pushed, closing.
