### ISSUE TITLE
Moving to CoffeeScript

### ISSUE THREAD

**Issue by deathbeam** [deathbeam/yae#12]
In next update engine language will be moving to [CoffeeScript](http://coffeescript.org). This will solve multi-threading bugs and allows me to focus on features development and I will not be worried about both JS and Lua support. So I am asking you if it is fine.

For everyone who already started project in .js, here is tool what will convert your code: http://js2.coffee

**Comment by andrewrobinson5** [comment]
can I still use javascript as code? Is it a complete new syntax?

**Comment by deathbeam** [comment]
Coffeescript compiles to JavaScript and Coffeescript is basically only simplified JavaScript, so it have also similar syntax

**Comment by deathbeam** [comment]
Hmm at end I decided to not remove support for JavaScript, as for performance reasons I had to create system what compiles CoffeeScript files to JavaScript files during build, so simply not using .coffee extension and using .js extension will work. But in Wiki, tutorials will be for CoffeeScript, but as they are similar (almost same) you can easily adapt them to JavaScript

**Comment by deathbeam** [comment]
New version released: 2df775d1cc39ff3849a95d7bdf1106202a01be92
