### ISSUE TITLE
Upcoming update

### ISSUE THREAD

**Issue by deathbeam** [deathbeam/yae#13]
In upcoming update I will be probably moving back from CoffeeScript to only JavaScript. This will let me work more on Web support and also possibility to add debugger to Nide. What do you think? Also, sorry for this language changes, non is still in early development, but this move back to JavaScript will be probably final.

**Comment by andrewrobinson5** [comment]
Okay, web support seems promising in this engine and I'm looking forward to
seeing it.

**Comment by deathbeam** [comment]
Closing, 3.6.0 released 5703bf69483c6104d50f15bf78aa1bb8748fa636
