### ISSUE TITLE
": No such file or directory" when creating Hello project

### ISSUE THREAD

**Issue by PaulKlumpp** [deathbeam/yae#17]
Hi there,
good job with Non. I've been waiting for Löve to have some official Android and iOS support. But, ofc, that's a long shot. Also, LuaJIT won't be allowed on iOS. So, non is the correct leap forwards.
Now, I'm considering using non for more projects to come.

But I came across some small problems:

```
paul@dabura ~/dev/emptyy $ non hello
Generating Hello World! project
/usr/bin/env: bash
: No such file or directory

Task finished with non-zero result

BUILD FAILED
Total time: 0 seconds
/usr/bin/env: bash
: No such file or directory
paul@dabura ~/dev/emptyy $
```

Only the .non directory has been created. assets/ and config.yml is missing. See here:

```
paul@dabura ~/dev/emptyy $ ls -la
total 26
drwxr-xr-x  3 paul paul   3 Apr  5 03:23 .
drwx------ 84 paul paul 176 Apr  5 03:23 ..
drwxr-xr-x 11 paul paul  19 Apr  5 03:23 .non
```

There must be some small typo with a ":". Because env is in its correct place:

```
paul@dabura ~/dev/emptyy $ which env
/usr/bin/env
```

My current luarocks are

```
paul@dabura ~/dev/emptyy $ luarocks list

Installed rocks:
----------------

alt-getopt
   0.7.0-1 (installed) - /home/paul/.luarocks/lib/luarocks/rocks

lpeg
   0.12.2-1 (installed) - /home/paul/.luarocks/lib/luarocks/rocks

luafilesystem
   1.6.3-1 (installed) - /home/paul/.luarocks/lib/luarocks/rocks

moonscript
   0.3.1-1 (installed) - /home/paul/.luarocks/lib/luarocks/rocks

non
   0.6.4-1 (installed) - /home/paul/.luarocks/lib/luarocks/rocks
```

I am using Sabayon Linux, which essentially is a Gentoo Linux.

And, perhaps jdk version matters? :)

```
paul@dabura ~/dev/emptyy $ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (Gentoo package icedtea-7.2.5.4)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```

**Comment by PaulKlumpp** [comment]
Perhaps jdk version matters? :)
```
paul@dabura ~/dev/emptyy $ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (Gentoo package icedtea-7.2.5.4)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```

**Comment by deathbeam** [comment]
Your JDK is good. Try and run "which bash" or "type bash". Also, redoing API to be mostly compatible with LOVE and porting most of Lua library code to Java, so it will also increase performance.

**Comment by PaulKlumpp** [comment]
```
paul@dabura ~/dev/emptyy $ which bash
/bin/bash
paul@dabura ~/dev/emptyy $ type bash
bash is /bin/bash
paul@dabura ~/dev/emptyy $ bash --version
GNU bash, version 4.3.33(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I really don't get behind that error...

**Comment by deathbeam** [comment]
So it seems that your "bash" is installed in bin/bash but engine is trying to load it from usr/bin/env/bash/ . Try to create link in usr/bin/env/bash to bin/bash

**Comment by PaulKlumpp** [comment]
I think I got it.
After I finally got to know where that ":" error comes from. It came from "gradlew".

```
paul@dabura ~/dev/emptyy/.non $ ./gradlew 
: No such file or directory
paul@dabura ~/dev/emptyy/.non $ dos2unix ./gradlew 
dos2unix: converting file ./gradlew to Unix format...
paul@dabura ~/dev/emptyy/.non $ ./gradlew 
gradlew
./gradlew
Configuration on demand is an incubating feature.
> Configuring > 0/5 projects > root project
```

Please be sure you convert EOL to unix style for Linux scripts.

**Comment by PaulKlumpp** [comment]
```
#!/usr/bin/env bash
```

... could not work because the EOL was wrong.

**Comment by PaulKlumpp** [comment]
If you want, you can have permanent access to my 24/7 online desktop machine at home to test Linux packaging of nön.

**Comment by deathbeam** [comment]
Oh hmm I thought Git handles this for me. Maybe I was wrong. Thank you for finding this.

**Comment by deathbeam** [comment]
I probably fixed this, can you test it on your PC by installing latest dev version (see [Working from source](https://github.com/non2d/non/wiki/Working-from-source) tutorial)?

**Comment by deathbeam** [comment]
Tested this on Arch Linux (installed it only because of this issue) and it is working, so closing this issue.
