### ISSUE TITLE
Native Lua

### ISSUE THREAD

**Issue by deathbeam** [deathbeam/yae#21]
I want to replace LuaJ with [luajava](https://github.com/jasonsantos/luajava) for big performance boost. I just need pre-compiled luajava (along with latest Lua for iOS and for rest of platforms with latest LuaJIT) natives for
- android32
- ios32
- linux32
- linux64
- macosx32
- macosx64
- windows32
- windows64

If anyone is able to cross-compile natives for any of that platforms (for Android it must be for both ARM and x86) it would be great and will save me tons of work. Maybe we can use something like libGDX is doing [here](https://github.com/libgdx/libgdx/tree/master/gdx/jni) but as I do not own Mac I cannot make natives for iOS and Mac OS X.

**Comment by tangzero** [comment]
I can help you with the Mac natives.

**Comment by deathbeam** [comment]
Really? That would be great.

**Comment by deathbeam** [comment]
So, to make them simply fork [non.luajava](https://github.com/non2d/non.luajava) and run 

``` shell
ant compile-macosx
```

and then

``` shell
ant pack-macosx
```

And create pull request to non.luajava with built natives (will be created to libs/ directory)

**Comment by deathbeam** [comment]
[Native Lua backend](https://github.com/nondev/nonlua) is almost finished. Hopefully I will finish new release of NON soon.

**Comment by deathbeam** [comment]
Closing this, decided to use different way (AOT Java bytecode compiling).
