### ISSUE TITLE
[QUESTION] building on luarocks comes up with errors

### ISSUE THREAD

**Issue by lewislepton** [deathbeam/yae#22]
hello,

just spotted your project. and have to say im impressed. though on installing NON through terminal using luarocks, it pops up with some error. dont know how to fix really

here is what the terminal is saying

thanks

```
lepton:~ lepton$ luarocks install non

Error: Your user does not have write permissions in /usr/local 
-- you may want to run as a privileged user or use your local tree with --local.
lepton:~ lepton$ sudo luarocks install non

Error: No results matching query were found.
```

**Comment by deathbeam** [comment]
Right now on LuaRocks is outdated NON version which have Lua 5.1 as required artifact, so if you are running newer Lua, LuaRocks will fail to resolve it. Download NON from GitHub, cd into tools directory and run ./install.

**Comment by deathbeam** [comment]
Also, run install script as super user.
