### ISSUE TITLE
[QUESTION] how secure is NON

### ISSUE THREAD

**Issue by lewislepton** [deathbeam/yae#23]
hello again.

just to ask.
this looks like LOVE2D, just its outlook. though seems very different as well. but one problem i always had with LOVE2D is the security of files and how things are built in an application

im a mac user myself, and found that i could find files of .lua code in the application, thorugh the right-clickn, show contents etc.
does NON address this and fix this problem. i have not built anything yet, but just want to find out about it to see if its secure.

whilst i know nothing is 100% secure and people can find ways, i just dont need code so easy to find really like what LOVE2D does with applications

thanks

**Comment by deathbeam** [comment]
Right now, it works similar to Love2D, so users can view your source Lua code when they will decompress JAR or APK file. But, NON comes with built-in signer, so if you will sign your application, users will be able to see your Lua code, but not edit it.

**Comment by deathbeam** [comment]
Here is link to [tutorial](https://github.com/non2d/non/wiki/Signing-your-application) on how to sign your application.
