### ISSUE TITLE
[REQUEST] DVORAK layout support

### ISSUE THREAD

**Issue by lewislepton** [deathbeam/yae#25]
one thing i noticed right away when trying the example is tha NON is not supported for other keyboard layouts other than i guess QWERTY

i personally type in DVORAK and sure that many others do. i think for an update more keyboard layouts would be best supoorted, just in case ;)

**Comment by deathbeam** [comment]
NON input system is based on integer keycodes what are converted to strings and passed to Lua. So NON is not dependent on keyboard layout. If you will change your keyboard layout to QWERTZ, QWERTY or anything else, NON should recognize them.
