### ISSUE TITLE
[QUESTION] How to install non without LuaRocks?

### ISSUE THREAD

**Issue by ghost** [deathbeam/yae#28]
So LuaRocks appears to not be working with Non when I have Lua 5.3.

I have gotten non from github and have attempted to install it that way, using the install script. However even after running the install script, it appears to not be installed. I cannot run the "non" command (it says it doesn't exist).

I am running on Linux, specifically Kubuntu 15.04. I am a noob when it comes to linux so any help would be appreciated getting Non up and running.

**Comment by deathbeam** [comment]
Try to install latest development version (which should also work with Lua 5.3):

```
luarocks install --server=http://luarocks.org/dev non
```

Edit: Also, install script only builds non.jar launcher in bin folder which has to be manually added to your path. Because of this I am using LuaRocks, so it automates this process for me.

**Comment by ghost** [comment]
This worked. Thank you.
