### ISSUE TITLE
[QUESTION] Luarocks dev build failing

### ISSUE THREAD

**Issue by ghost** [deathbeam/yae#29]
So I used the luarocks dev build of non (as per your previous recommendation) and found this issue when attempting to generate the Hello World project (or any other project, in fact this issue always comes up for me).

http://imgur.com/a/bvMU5

Any help with this would be greatly appreciated. Thank you veryveryvery much.

**Comment by deathbeam** [comment]
Right now, current development version has small bug, and that is you must run all non commands as superuser. This will be fixed in upcoming release. But for now this bug also causes that all files generated by Hello World command requires superuser to edit them.

**Comment by ghost** [comment]
Thank you, I will run it as superuser from now on. Sorry for all the questions :P
