### ISSUE TITLE
3D module

### ISSUE THREAD

**Issue by deathbeam** [deathbeam/yae#30]
I want to add the 3D module to engine. What do you think about it? Also, what should be the module name? And API? I am not skilled with 3D stuff, so I want to know what needs to be in it and how should it look to be simple?

I thought about few module names:

I do not like this because then correct way would be to rename graphics to graphics2D and that would break LOVE compatibility

``` moonscript
non.graphics3D
```

This should be weird, because graphics module is 2D and it will have 3D sub-module

``` moonscript
non.graphics.3D
```

This is only fun idea:

``` moonscript
g3D = non.graphics.newDimension
```

**Comment by takaaptech** [comment]
I think we should focus on 2D, example projects, demo IAP and ads network. It is awesome if we have some example projects that demo ads network and IAP out here!
