### ISSUE TITLE
Better "non init" command

### ISSUE THREAD

**Issue by deathbeam** [deathbeam/yae#32]
I want to make better `non init` command. As, right now it simply creates "Hello World" project. Sorry for posting all the issues by myself, but as I want to have development process transparent, I am putting this here if anyone will have any better idea. It is good to listen to others when working on things like this engine and I love to listen to any feedback :smile:

So, new command will probably look like one of those below:

This is the most common way

```
non init --name MyProject --package com.mycompany.myproject
```

This is a bit shorter way:

```
non init -name MyProject -package com.mycompany.myproject
```

Even shorter (but less self-explaining)

```
non init -n MyProject -p com.mycompany.myproject
```

And shortest one (and not self explaining at all):

```
non init MyProject package com.mycompany.myproject
```

I can change last one to work better with multiple words project names:

```
non init com.mycompany.myproject "My awesome project"
```

But that is really unclean imo. And of course, when one of vars will not be passed, builder will use default "Hello World" vars.

So, anyone? Is anyone even looking at my issues? I would like to hear something from you :)

**Comment by desk467** [comment]
an idea would be to create a global file to general settings (to define the company name, for example) and, on "non init" command, you just write the name of the game, and the package name will be automatically generated

**Comment by deathbeam** [comment]
Hmm that is interesting idea. But for Android deployement, package name is important (I am not sure about iOS) and then you will partly lose control above it.

**Comment by bdjnk** [comment]
I agree with @desk467 on `non init MyProject`. The package name could be auto generated `com.username.myproject`, which would be part of the `init` output along with a note on how to change it.

**Comment by deathbeam** [comment]
I can get current logged in username and use that, but it is hard to remove all sort of accents and diacritic. But I will try. Thanks guys.

**Comment by deathbeam** [comment]
Closing this issue, added new init command based on yours suggestion here e8a02befe242f127e7d7384135ed20df30dcf8e6 . It is untested right now, so sorry if it will not be working immediatelly.

**Comment by bdjnk** [comment]
I'd replace spaces with underscores, instead of removing them. Other than that, it looks good

**Comment by deathbeam** [comment]
It is used mainly for Java package names, and underscores are no-no there.

**Comment by bdjnk** [comment]
Underscores are allowed, as described by the [Java package naming documentation](http://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).

**Comment by deathbeam** [comment]
Hmm okay then, anyway I found there some bugs, so I fixed them right now and gonna update that spaces to underscores.

**Comment by deathbeam** [comment]
Done here de9ab51b092250429267457f85a5198ec94a35b7
