### ISSUE TITLE
Top level modules?

### ISSUE THREAD

**Issue by deathbeam** [deathbeam/yae#33]
What about changing current all-in-one-global module scheme to be split for each module? Example:

Currently, we have this:

```
image = non.graphics.newImage "batman.png"
music = non.audio.newSource "something.ogg"

non.load = ->
  non.audio.play music

non.draw = ->
  non.graphics.draw image, 10, 10
```

But in NÖN we also have `java` and `config` globals. And I am also going to add testing module with global `test`. So, right now it is a bit weird. And to support LÖVE projects, I can add LÖVE compat snippet which will create `love` module with all modules correctly mapped to it. So above will be:

```
image = graphics.newImage "batman.png"
music = audio.newSource "something.ogg"

load = ->
  audio.play music

draw = ->
  graphics.draw image, 10, 10
```

This will also solve issue #30 because I will be able to simply add graphics3D global and it will not look ugly. What do you think?

**Comment by deathbeam** [comment]
Also, this will make this project not look like port of LÖVE, but it will still have support for LÖVE projects.
And goal of this project is to make games without any nonsense, and typing `non.` before everything is redundant and so it is adding more nonsense to engine :smile:

**Comment by bdjnk** [comment]
If you're not worried about name collisions, removing the non namespace makes sense to me.

**Comment by deathbeam** [comment]
As this is standalone engine (no LuaRocks conflicts), name collisions wouldn't be a problem.

**Comment by pandinocoder** [comment]
Personally I think that the support either-or would be a good idea, making
all of the following valid:

```
image = non.graphics.newImage "batman.png"
music = non.audio.newSource "something.ogg"

non.load = ->
  non.audio.play music

non.draw = ->
  non.graphics.draw image, 10, 10
```

```
image = graphics.newImage "batman.png"
music = audio.newSource "something.ogg"

load = ->
  audio.play music

draw = ->
  graphics.draw image, 10, 10
```

```
image = love.graphics.newImage "batman.png"
music = love.audio.newSource "something.ogg"

love.load = ->
  love.audio.play music

love.draw = ->
  love.graphics.draw image, 10, 10
```

And the way to loop all of this in would be to do something akin to the
following, outside of developer space. Not entirely sure how the `non` module
is created at the moment, but this would essentially be done immediately after:

```
love = non
graphics = non.graphics
audio = non.audio
```

The justification for all of this is simply maximum compatibility with zero
trust in the user (of non, so they'd actually be a developer) to do the right
thing. While this seems unclean from the perspective of a framework designer,
this has the potential to drastically reduce if not eliminate stupid issues
being created asking "why is love not defined?" or "why is non not defined?".

Also I propose the following change, again out of developer space:

```
non.graphics = non.graphics2d
graphics2d = non.graphics2d
graphics = non.graphics
```

I believe that this change is also worth doing because it makes the graphics3d
module stand out a little bit less (given the essentially "uppercase" 3).

Thoughts?

**Comment by deathbeam** [comment]
Entire `non` module is created [here](https://github.com/nondev/non/blob/master/src/non.moon).

And I am not sure about that because I do not like philosophy of doing one thing multiple ways. What you reccomened will make this valid:

```
image = love.graphics.newImage "batman.png"
music = audio.newSource "something.ogg"

non.load = ->
  love.audio.play music

draw = ->
  graphics2d.draw image, 10, 10

love.quit = ->
  non.system.quit!
```

Which is a bit weird (and I know extreme case, but possible).

**Comment by pandinocoder** [comment]
That being said, it already works that way from my understanding, just global modules don't exist so they aren't thrown into the fray.

**Comment by deathbeam** [comment]
Got an idea. I will make all modules global, and to create `non` namespace, you will do:

```
non = require "non"
```

And for love, simply

```
love = require "love"
```

So we will prefer explicit declaration above implicit declaration.

**Comment by pandinocoder** [comment]
But won't this still permit interleaved behavior between global and non-global modules?

**Comment by deathbeam** [comment]
Yes it does, but not by default and users will be able to enable it manually.

**Comment by deathbeam** [comment]
I decided to leave it as it is and move `config` and `java` to `non.config` and `non.java`. I did tihat in this commit 0e69914c371b5522a37029eb3ddc5ee1418b8833.

Why? Because in MoonScript there exists awesome [import](http://moonscript.org/reference/#import_statement) statement. Example:

``` moonscript
import graphics, config, java from non

graphics.draw something
```

**Comment by ghost** [comment]
For the record, this isn't as pretty, but does the same thing!

``` moonscript
{:graphics, :config, :java} = non
```

There was actually a discussion on the import statement in the MoonScript repository, and it might receive a change in the future if leafo is inclined enough. May or may not be relevant to NON itself, but just wanted to let you know.

**Comment by deathbeam** [comment]
@Kingdaro I find that code pretty. And thank you for that info. Hopefully he will not remove `import`.
