### ISSUE TITLE
Luarocks install not working.

### ISSUE THREAD

**Issue by supernintendo** [deathbeam/yae#35]
Hi,

When running `luarocks install non` I get `Error: No results matching query were found.`. Additionally, attempting to install from the rockspec file produces the following error:

```
sh: build.sh: No such file or directory

Error: Build error: Failed building.
```

This is on Mac OS X 10.11, with luarocks 2.2.2 configured to use Lua 5.2.

**Comment by desk467** [comment]
try this: luarocks install --server=http://luarocks.org/dev non

I had the same problem, then i changed by this command above and it worked

**Comment by supernintendo** [comment]
@desk467 Hmm, still getting the `sh: build.sh: No such file or directory` error. Cloning the repo and then running `luarocks install non-dev-1.rockspec` from the directory works, however, which indicates that this may be an issue with my luarocks configuration.
