### ISSUE TITLE
Error in java compiling after following wiki tutorials

### ISSUE THREAD

**Issue by andrewrobinson5** [deathbeam/yae#4]
I keep getting the following java errors when trying to follow the wiki pages. When I try to run, this happens.

![image](https://cloud.githubusercontent.com/assets/9408593/5693101/eeb2b57e-98d3-11e4-971e-21b5cb4d69e8.png)

What am I supposed to do?

**Comment by andrewrobinson5** [comment]
It did that when I tried running pong demo too.

**Comment by deathbeam** [comment]
It is maybe problem with using word package in package declaration, when I will get home today, I will check it.

**Comment by deathbeam** [comment]
Did you run java -jar non.jar update before trying to run it? Also, run task is not correctly working right now, use dist task and manually run executable jar.
