### ISSUE TITLE
Can't use engine when building from source.

### ISSUE THREAD

**Issue by andrewrobinson5** [deathbeam/yae#5]
I've followed the tutorials exactly and it seems like the engine has lots of bugs. I'm excited to see what this engine is capable of, but I can't as long as it keeps this stuff up.

I got yet another error while trying to generate the programs from a jar I just built from source code following the wiki: Error: Could not find or load main class launcher.Main

(also, in the wiki page WORKING FROM SOURCE, the -C needs to be lowercase to actually create the jar.)

**Comment by deathbeam** [comment]
No, C must be uppercase, really. And yes, I am working on new commit, use releases, master branch isn't stable when working on new update.

**Comment by andrewrobinson5** [comment]
when I tried to use -C and it brought up a list of commands for java. only -c made the jar.

**Comment by deathbeam** [comment]
and didnt you forgot to add dot at end of command? Maybe you didn't saw it first

**Comment by andrewrobinson5** [comment]
Oh, that seemed to work, thanks. I really like this engine. It shows lots of promise.

**Comment by andrewrobinson5** [comment]
Thanks for making such a great engine for me to use! here's my test program: 
![image](https://cloud.githubusercontent.com/assets/9408593/5697406/4bbecc80-99b5-11e4-82e3-56105c7d682c.png)

Image placement was a bit off but, i love the engine.
