### ISSUE TITLE
Sound not working.

### ISSUE THREAD

**Issue by andrewrobinson5** [deathbeam/yae#6]
I'm sorry to keep posting issues every time I need help, but I have no other way to contact you. I'm trying to follow the wiki pages but, I need an example to actually learn well. I was trying out sound and background music for my game, but It just showed the loading screen and when I clicked to enter the game, it closed the window. I don't know what is wrong. Also, how do I add a collider to an image with box2d? I am trying to make a platformer style combat game.

**Comment by deathbeam** [comment]
Oh, I am really sorry, I forgot to update wiki for Sounds and Music. That ", true" when trying to load sound is not present in engine. Updating wiki page for it.

**Comment by deathbeam** [comment]
And, collider to image? Simply draw image with position and rotation of Box2D body, something like this:

``` javascript
// JavaScript
body = network.body(.....);
......
graphics.draw(sometexture, body.getPosition().x, body.getPosition().y, body.getAngle());
```

**Comment by andrewrobinson5** [comment]
Okay thanks, ur a lifesaver. Is there any other way I can contact you like e-mail or something? I some of my questions aren't issues, just help that I need.

**Comment by deathbeam** [comment]
You can mail me at slusnucky@gmail.com
