### ISSUE TITLE
Latest version, 3.2.1 says everything fails when it didn't

### ISSUE THREAD

**Issue by andrewrobinson5** [deathbeam/yae#7]
Not incredibly important but, whenever I do anything in the cmd for non.jar, it says it failed when it completed everything like it is supposed to.

**Comment by deathbeam** [comment]
For me, it is working:

<img src="http://i.imgur.com/rTVZeFM.png" />

**Comment by andrewrobinson5** [comment]
wow. For me it isn't. I can overlook it though.
